service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  region: eu-central-1
  stage: dev

functions:
  hello:
    handler: handler.migrate
    events:
      - http:
          path: v1/{any+}
          method: ANY
